### ISSUE TITLE
Further additions and corrections

### ISSUE THREAD

**Issue by kostasvar** [numbbo/coco-doc#10]
This issue is for spotting further additions or possibly corrections for the documentation.
 
- Among the non-normalized functions with `gamma(n)` is also the Griewank-Rosenbrock function. 

- In the function definition section, we could say a few words about Rosenbrock and rotated Rosenbrock and the different scaling of variables compared to `bbob`, that now is only presented in the table.

**Comment by brockho** [comment]
Solved with pr #11.
